server:
  port: 8082

upload:
  path: /upload/socketing/thumbnails

spring:
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event_domain
    username: username
    password: password
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
    org.springframework.web: debug
    org.springframework.web.servlet: debug
    org.springframework.web.client: debug
    org.springframework.boot.web: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true
  api-docs:
    path: /apis
  swagger-ui:
    path: /api-docs
    url: /apis
    operations-sorter: alpha
    disable-swagger-default-url: false
    display-request-duration: true
